# -*- coding: utf-8 -*-
"""proyecto_final_marketing_digital.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AfOo_aLkwqTKaYq8uh_5U2UrxD3CeQmZ

# Proyecto Final: Análisis de Campañas de Marketing Digital
**Módulo:** Procesamiento de Datos con Python — Technolochicas

**Problemática a resolver:** Una agencia de publicidad maneja decenas de
campañas digitales para distintos clientes y plataformas (Facebook Ads,
Google Ads, TikTok Ads, etc.). Los reportes de desempeño llegan de
distintas fuentes con formatos inconsistentes, columnas incompletas y
registros duplicados, lo que dificulta comparar el rendimiento real de
cada campaña y tomar decisiones de inversión publicitaria.

**Objetivo del proyecto:** limpiar y procesar el histórico de campañas,
calcular métricas clave de desempeño y generar insights que ayuden a decidir en qué plataformas, clientes y segmentos de audiencia conviene invertir más presupuesto.

## 1. Importación y manejo de datos
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from functools import reduce

sns.set_theme(style="whitegrid")
pd.set_option("display.max_columns", None)

# Importación del conjunto de datos desde un archivo CSV (fuente externa)
try:
    df = pd.read_csv("campanas_marketing_digital.csv")
    print(f"Datos importados correctamente: {df.shape[0]} filas, {df.shape[1]} columnas")
except FileNotFoundError as e:
    raise SystemExit(f"No se encontró el archivo de datos: {e}")

"""### Exploración inicial"""

df.head()

df.info()

df.describe()

print("Valores nulos por columna:")
print(df.isnull().sum())

print(f"Filas duplicadas: {df.duplicated().sum()}")

"""## 2. Limpieza de datos"""

df_limpio = df.copy()

# 2.1 Eliminar duplicados exactos
filas_antes = len(df_limpio)
df_limpio = df_limpio.drop_duplicates()
print(f"Duplicados eliminados: {filas_antes - len(df_limpio)}")

# 2.2 Corregir errores de formato en texto
columnas_texto = ["cliente", "plataforma", "objetivo", "segmento_edad"]
for col in columnas_texto:
    df_limpio[col] = df_limpio[col].astype(str).str.strip().str.title()
    df_limpio[col] = df_limpio[col].replace("Nan", np.nan)

# 2.3 Normalizar fechas con múltiples formatos
def normalizar_fecha(valor):
    """Intenta parsear una fecha en varios formatos posibles y devuelve NaT si falla."""
    formatos = ["%Y-%m-%d", "%d/%m/%Y", "%d-%m-%y"]
    for formato in formatos:
        try:
            return pd.to_datetime(valor, format=formato)
        except (ValueError, TypeError):
            continue
    return pd.NaT

df_limpio["fecha"] = df_limpio["fecha"].apply(normalizar_fecha)
print(f"Fechas no reconocidas tras la normalización: {df_limpio['fecha'].isna().sum()}")

# 2.4 Corregir valores negativos (el gasto no puede ser negativo)
df_limpio["gasto_mxn"] = df_limpio["gasto_mxn"].apply(lambda x: abs(x) if pd.notna(x) else x)

# 2.5 Tratamiento de valores faltantes
# Conversiones y segmento/plataforma faltantes: no se puede inventar el dato,
# se marcan para no distorsionar promedios.
df_limpio["conversiones"] = df_limpio["conversiones"].fillna(0)
df_limpio["segmento_edad"] = df_limpio["segmento_edad"].fillna("No especificado")
df_limpio["plataforma"] = df_limpio["plataforma"].fillna("No especificado")

# Gasto e ingresos faltantes: se imputan con la mediana de su propia plataforma,
# más robusta que la media ante campañas con gasto muy alto o muy bajo.
for col in ["gasto_mxn", "ingresos_mxn"]:
    df_limpio[col] = df_limpio.groupby("plataforma")[col].transform(
        lambda serie: serie.fillna(serie.median()))
    df_limpio[col] = df_limpio[col].fillna(df_limpio[col].median())

# 2.6 Eliminar filas sin fecha válida (no se puede analizar tendencia temporal sin fecha)
df_limpio = df_limpio.dropna(subset=["fecha"])

print("\nValores nulos después de la limpieza:")
print(df_limpio.isnull().sum())
print(f"\nFilas finales tras la limpieza: {len(df_limpio)}")

"""## 3. Manipulación de datos"""

# 3.1 Reindexar y renombrar columnas según convención snake_case
df_limpio = df_limpio.rename(columns={"ingresos_mxn": "ingresos_mxn", "gasto_mxn": "gasto_mxn"})
df_limpio = df_limpio.reset_index(drop=True)

# 3.2 Operaciones aritméticas y de manipulación en series para crear métricas de desempeño
df_limpio["ctr_pct"] = (df_limpio["clics"] / df_limpio["impresiones"] * 100).round(2)
df_limpio["tasa_conversion_pct"] = np.where(
    df_limpio["clics"] > 0,
    (df_limpio["conversiones"] / df_limpio["clics"] * 100).round(2),
    0.0,)
df_limpio["cpa_mxn"] = np.where(
    df_limpio["conversiones"] > 0,
    (df_limpio["gasto_mxn"] / df_limpio["conversiones"]).round(2),
    np.nan,)
df_limpio["roas"] = np.where(
    df_limpio["gasto_mxn"] > 0,
    (df_limpio["ingresos_mxn"] / df_limpio["gasto_mxn"]).round(2),
    np.nan,)
df_limpio["utilidad_mxn"] = (df_limpio["ingresos_mxn"] - df_limpio["gasto_mxn"]).round(2)
df_limpio["mes"] = df_limpio["fecha"].dt.to_period("M").astype(str)

df_limpio[["id_campana", "ctr_pct", "tasa_conversion_pct", "cpa_mxn", "roas", "utilidad_mxn"]].head()

# 3.3 Filtrado y ordenamiento para extraer información relevante
top_campanas = df_limpio.sort_values("roas", ascending=False).head(10)
top_campanas[["id_campana", "cliente", "plataforma", "roas", "utilidad_mxn"]]

campanas_perdida = df_limpio[df_limpio["utilidad_mxn"] < 0].sort_values("utilidad_mxn")
print(f"Campañas con utilidad negativa: {len(campanas_perdida)} de {len(df_limpio)}")
campanas_perdida[["id_campana", "cliente", "plataforma", "gasto_mxn", "ingresos_mxn", "utilidad_mxn"]].head()

"""## 4. Análisis exploratorio con Pandas"""

resumen_plataforma = df_limpio.groupby("plataforma").agg(
    num_campanas=("id_campana", "count"),
    gasto_total=("gasto_mxn", "sum"),
    ingresos_total=("ingresos_mxn", "sum"),
    ctr_prom=("ctr_pct", "mean"),
    conversion_prom=("tasa_conversion_pct", "mean"),
    roas_prom=("roas", "mean"),
).round(2).sort_values("roas_prom", ascending=False)

resumen_plataforma

resumen_cliente = df_limpio.groupby("cliente").agg(
    gasto_total=("gasto_mxn", "sum"),
    ingresos_total=("ingresos_mxn", "sum"),
    utilidad_total=("utilidad_mxn", "sum"),
    roas_prom=("roas", "mean"),
).round(2).sort_values("utilidad_total", ascending=False)

resumen_cliente

resumen_segmento = df_limpio.groupby("segmento_edad").agg(
    conversion_prom=("tasa_conversion_pct", "mean"),
    cpa_prom=("cpa_mxn", "mean"),
).round(2).sort_values("conversion_prom", ascending=False)

resumen_segmento

"""## 5. Aplicación de funciones, lambda, excepciones y map/filter/reduce"""

def clasificar_desempeno(roas):
    """Clasifica una campaña según su ROAS (retorno sobre inversión publicitaria)."""
    try:
        if pd.isna(roas):
            return "Sin datos"
        if roas >= 3:
            return "Excelente"
        elif roas >= 1.5:
            return "Bueno"
        elif roas >= 1:
            return "Regular"
        else:
            return "Bajo"
    except TypeError:
        return "Dato inválido"

df_limpio["desempeno"] = df_limpio["roas"].apply(clasificar_desempeno)
df_limpio["desempeno"].value_counts()

# Función lambda para etiquetar campañas de alto gasto
umbral_alto_gasto = df_limpio["gasto_mxn"].quantile(0.75)
df_limpio["alto_gasto"] = df_limpio["gasto_mxn"].apply(lambda g: "Sí" if g >= umbral_alto_gasto else "No")

# map(): convertir el ROAS a una etiqueta de riesgo usando una función simple
def etiqueta_riesgo(roas):
    if pd.isna(roas):
        return "N/D"
    return "Riesgo alto" if roas < 1 else "Riesgo controlado"

df_limpio["riesgo"] = list(map(etiqueta_riesgo, df_limpio["roas"]))

# filter(): obtener los IDs de campañas "estrella" (excelente desempeño y alta conversión)
ids_campanas_estrella = list(filter(
    lambda id_: df_limpio.set_index("id_campana").loc[id_, "desempeno"] == "Excelente"
    and df_limpio.set_index("id_campana").loc[id_, "tasa_conversion_pct"] > 5,
    df_limpio["id_campana"].head(200)))
print(f"Campañas estrella encontradas (muestra): {len(ids_campanas_estrella)}")

# reduce(): calcular el gasto total invertido, acumulando con una función personalizada
gasto_total_reduce = reduce(lambda acumulado, valor: acumulado + valor, df_limpio["gasto_mxn"], 0)
print(f"Gasto total invertido (via reduce): ${gasto_total_reduce:,.2f} MXN")

def calcular_roi_seguro(ingresos, gasto):
    """Calcula el ROI manejando división entre cero y valores no numéricos."""
    try:
        ingresos = float(ingresos)
        gasto = float(gasto)
        if gasto == 0:
            raise ZeroDivisionError("El gasto no puede ser cero para calcular ROI")
        return round(((ingresos - gasto) / gasto) * 100, 2)
    except ZeroDivisionError:
        return np.nan
    except (ValueError, TypeError):
        return np.nan

df_limpio["roi_pct"] = df_limpio.apply(
    lambda fila: calcular_roi_seguro(fila["ingresos_mxn"], fila["gasto_mxn"]), axis=1)
df_limpio[["id_campana", "roi_pct"]].head()

"""## 6. Visualizaciones y hallazgos"""

fig, ax = plt.subplots(figsize=(9, 5))
datos_roas = resumen_plataforma["roas_prom"].sort_values()
colores_barras = sns.color_palette("husl", len(datos_roas))
datos_roas.plot(kind="barh", ax=ax, color=colores_barras)
ax.set_xlabel("ROAS promedio")
ax.set_ylabel("Plataforma")
ax.set_title("ROAS promedio por plataforma publicitaria")
plt.tight_layout()
plt.savefig("grafico_roas_plataforma.png", dpi=150)
plt.show()

fig, ax = plt.subplots(figsize=(9, 5))
gasto_mensual = df_limpio.groupby("mes")["gasto_mxn"].sum().sort_index()
ingresos_mensual = df_limpio.groupby("mes")["ingresos_mxn"].sum().sort_index()
ax.plot(gasto_mensual.index, gasto_mensual.values, marker="o", label="Gasto")
ax.plot(ingresos_mensual.index, ingresos_mensual.values, marker="o", label="Ingresos")
ax.set_title("Gasto vs. Ingresos por mes")
ax.set_xlabel("Mes")
ax.set_ylabel("MXN")
ax.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("grafico_gasto_ingresos_mensual.png", dpi=150)
plt.show()

fig, ax = plt.subplots(figsize=(7, 5))
df_limpio["desempeno"].value_counts().reindex(
    ["Excelente", "Bueno", "Regular", "Bajo", "Sin datos"]).plot(kind="bar", ax=ax, color="#A23B72")
ax.set_title("Distribución de campañas por nivel de desempeño (ROAS)")
ax.set_xlabel("Desempeño")
ax.set_ylabel("Número de campañas")
plt.tight_layout()
plt.savefig("grafico_distribucion_desempeno.png", dpi=150)
plt.show()

fig, ax = plt.subplots(figsize=(8, 5))
sns.barplot(data=resumen_segmento.reset_index(), x="segmento_edad", y="conversion_prom", ax=ax, color="#F18F01")
ax.set_title("Tasa de conversión promedio por segmento de edad")
ax.set_xlabel("Segmento de edad")
ax.set_ylabel("Tasa de conversión (%)")
plt.tight_layout()
plt.savefig("grafico_conversion_segmento.png", dpi=150)
plt.show()

"""## 7. Conclusiones e insights

(Ver reporte de análisis en Word para la interpretación completa de
resultados y recomendaciones futuras basadas en estos resultados.)
"""

print("Resumen general del análisis")
print("=" * 40)
print(f"Total de campañas analizadas: {len(df_limpio)}")
print(f"Gasto total: ${df_limpio['gasto_mxn'].sum():,.2f} MXN")
print(f"Ingresos totales: ${df_limpio['ingresos_mxn'].sum():,.2f} MXN")
print(f"ROAS promedio general: {df_limpio['roas'].mean():.2f}")
print(f"Plataforma con mejor ROAS: {resumen_plataforma['roas_prom'].idxmax()}")
print(f"Cliente con mayor utilidad generada: {resumen_cliente['utilidad_total'].idxmax()}")

df_limpio.to_csv("campanas_marketing_digital_procesado.csv", index=False)
print("Dataset procesado guardado como campanas_marketing_digital_procesado.csv")